# Generated by Django 2.0.5 on 2018-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat', models.IntegerField(default=None)),
                ('temperature', models.FloatField(default=None)),
            ],
        ),
    ]
